"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m4e)-=jiuki(o#s82j(ltb2(+@8ouu+&@_4111r^h89uz7f9tm'

# 允許 localhost, 127.0.0.1 以及 Docker 容器服務名稱
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'web', 'saas_django', '*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # DRF & Auth
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    
    # Allauth & OAuth Providers
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google Provider
    
    # Local apps
    'core',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 如果你使用 dj_rest_auth / authtoken
        'rest_framework.authentication.TokenAuthentication',
        # 如果使用 SimpleJWT
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# django.contrib.sites 所需的預設站台 ID
SITE_ID = 1

# 帳號驗證策略設定 (關閉一般帳密，強制使用 Google 登入)
ACCOUNT_LOGIN_METHODS = {'email'}   # 登入識別欄位採用 Email
ACCOUNT_SIGNUP_FIELDS = ['email*'] # 註冊必填欄位 (新版 allauth 語法)
SOCIALACCOUNT_QUERY_EMAIL = True     # 向 Google 授權頁面請求使用者 Email 權限

# 徹底關閉一般帳密註冊與郵件驗證 (全權交給 Google 驗證身分)
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 不需寄送信箱驗證信 (Google 已驗證過 email)
SOCIALACCOUNT_AUTO_SIGNUP = True     # 使用者第一次用 Google 登入時，自動建立帳號，不跳出二次確認表單
ACCOUNT_ALLOW_REGISTRATION = False   # 關閉傳統 Django 帳密註冊表單 (預防駭客直接 Post 一般註冊 API)


# Google OAuth 2.0 憑證與 Scope 設定 (透過環境變數保護 Client ID 與 Secret)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # 請求 Google 授權的範圍：取得使用者 basic profile (名字/頭像) 與 email
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',  # 不需要背景 offline 存取權 (不需要 refresh token)
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

# 允許 Next.js 前端 3000 Port 存取
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# 允許前端帶上自訂的 Header X-Organization-ID
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-organization-id", 
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'saas_db'),
        'USER': os.getenv('MYSQL_USER', 'saas_user'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'saas_password'),
        'HOST': os.getenv('MYSQL_HOST', 'localhost'),  # 容器環境下會是 'db'
        'PORT': os.getenv('MYSQL_PORT', '3306'),
    }
}

SILENCED_SYSTEM_CHECKS = ['models.W036']


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# 5. Swagger UI 靜態檔案路徑 (部署時收集靜態檔使用)
STATIC_ROOT = BASE_DIR / 'staticfiles'


AUTH_USER_MODEL = "core.User"


# 6. Redis 設定 (分散式鎖與快取)
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")


# Celery & RabbitMQ 訊息佇列設定
RABBITMQ_USER = os.getenv("RABBITMQ_DEFAULT_USER", "guest")
RABBITMQ_PASS = os.getenv("RABBITMQ_DEFAULT_PASS", "guest")
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "rabbitmq")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", "5672")

# Celery Broker 使用 RabbitMQ (amqp 協定)
CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//"

# 使用 Redis 作為 Task Result Backend (儲存異步任務執行結果)
CELERY_RESULT_BACKEND = REDIS_URL

# 訊息序列化格式設定
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# 商業級可靠性與死信佇列 (DLQ) 關鍵配置
CELERY_TASK_ACKS_LATE = True  # Worker 執行完畢並成功後才傳回 Ack，避免執行途中 Worker 崩潰丟失任務
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 每次只預取 1 個任務，防止長任務被個別 Worker 獨佔

# STRIPE 設定
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")


# 電子郵件設定
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)