"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m4e)-=jiuki(o#s82j(ltb2(+@8ouu+&@_4111r^h89uz7f9tm'

# Allow localhost, 127.0.0.1, Docker container service names, and wildcards
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'web', 'saas_django', '*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # DRF & Auth
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    
    # 1. Swagger / OpenAPI 3.0 auto-documentation generator
    'drf_spectacular',
    
    # Allauth & OAuth Providers
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Google Provider
    
    # Local apps
    'core',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # If using dj_rest_auth / authtoken
        'rest_framework.authentication.TokenAuthentication',
        # If using SimpleJWT
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 2. Specify OpenAPI schema generator for drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# 3. drf-spectacular configuration (Supports custom X-Organization-ID header)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Multi-Tenant SaaS Workspace API',
    'DESCRIPTION': 'Enterprise-grade SaaS platform with Multi-Tenancy RBAC, Stripe Billing, and Quota Engine.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'X-Organization-ID': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-Organization-ID',
                'description': 'Tenant Organization UUID',
            }
        }
    },
    'SECURITY': [{'X-Organization-ID': []}],
}

# Default Site ID required by django.contrib.sites
SITE_ID = 1

# Authentication strategy: Disable traditional password auth, enforce Google OAuth
ACCOUNT_LOGIN_METHODS = {'email'}   # Use email as the primary login identifier
ACCOUNT_SIGNUP_FIELDS = ['email*'] # Required signup field (latest allauth syntax)
SOCIALACCOUNT_QUERY_EMAIL = True     # Request user email permission during Google OAuth consent

# Disable traditional username/password registration and email verification (delegated to Google)
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip verification emails (pre-verified by Google)
SOCIALACCOUNT_AUTO_SIGNUP = True     # Automatically provision account on first Google login without prompt
ACCOUNT_ALLOW_REGISTRATION = False   # Disable traditional registration form (prevents direct POST signup abuse)


# Google OAuth 2.0 credentials and scope configuration (protected via environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Scopes requested: Basic profile (name/avatar) and email
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',  # No offline access needed (no refresh token required)
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Allowed origins for Next.js frontend client (Port 3000)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Allow custom X-Organization-ID header in CORS requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-organization-id',
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database Configuration (MySQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'saas_db'),
        'USER': os.getenv('MYSQL_USER', 'saas_user'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'saas_password'),
        'HOST': os.getenv('MYSQL_HOST', 'db'),  # Matches saas_mysql service 'db' on Docker Bridge network
        'PORT': os.getenv('MYSQL_PORT', '3306'),

        # Configure utf8mb4 charset and strict SQL mode
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

SILENCED_SYSTEM_CHECKS = ['models.W036']


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# 5. Static root path for collectstatic (used by Swagger UI & Admin in production)
STATIC_ROOT = BASE_DIR / 'staticfiles'


AUTH_USER_MODEL = 'core.User'


# 6. Redis configuration (Distributed locking and caching)
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')


# Celery & RabbitMQ Message Broker Configuration
RABBITMQ_USER = os.getenv('RABBITMQ_DEFAULT_USER', 'guest')
RABBITMQ_PASS = os.getenv('RABBITMQ_DEFAULT_PASS', 'guest')
RABBITMQ_HOST = os.getenv('RABBITMQ_HOST', 'rabbitmq')
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT', '5672')

# RabbitMQ Broker URL (AMQP Protocol)
CELERY_BROKER_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//'

# Use Redis as the Task Result Backend
CELERY_RESULT_BACKEND = REDIS_URL

# Serialization configuration
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Enterprise-grade reliability and task execution controls
CELERY_TASK_ACKS_LATE = True  # Acknowledge task only after completion to avoid task loss on worker crash
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Fetch one task per worker process to prevent queue hogging

# Stripe Payment & Billing Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

STRIPE_PRICE_PRO = os.getenv('STRIPE_PRICE_PRO', '')
STRIPE_PRICE_ENTERPRISE = os.getenv('STRIPE_PRICE_ENTERPRISE', '')


# SMTP Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)