# Generated by Django 5.2.16 on 2026-07-29 19:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='expires_at',
            field=models.DateTimeField(default=core.models.get_default_invitation_expiration, help_text='邀請連結過期時間 (預設 7 天)'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='token',
            field=models.CharField(blank=True, help_text='專屬邀請 Token', max_length=64, null=True, unique=True),
        ),
    ]
