# Generated by Django 5.2.16 on 2026-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationinvitation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='FREE', help_text='當前方案: FREE (5), PRO (30), ENTERPRISE (100)', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_projects',
            field=models.IntegerField(default=5, help_text='該方案允許的最大專案建立數量'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Pro Plan'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
    ]
