# Generated by Django 5.2.16 on 2026-07-29 13:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeeventlog',
            name='payload',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('canceling', 'Canceling at Period End'), ('incomplete', 'Incomplete')], default='active', max_length=20),
        ),
    ]
