# Generated by Django 5.2.17 on 2026-08-16 20:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_plan_subscription_max_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='monthly_api_quota',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Raw Markdown content'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='FREE', help_text='Current plan: FREE (5), PRO (25), ENTERPRISE (150)', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Workspace URL slug', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='expires_at',
            field=models.DateTimeField(default=core.models.get_default_invitation_expiration, help_text='Expiration timestamp for the invitation link (defaults to 7 days)'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='token',
            field=models.CharField(blank=True, help_text='Unique invitation token', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stripeeventlog',
            name='type',
            field=models.CharField(help_text='Stripe event type, e.g., checkout.session.completed', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_projects',
            field=models.IntegerField(default=5, help_text='Maximum allowed projects for this plan'),
        ),
    ]
